### PR TITLE
Remove Rooms from Database

### PR DESCRIPTION
**Pull request by EricBanker12**

### CODE REVIEW

**Comment by EricBanker12** [comment]
I noticed player.move does not account for return of None from room.get_room_north, but did not fix it here

Edit: I may have been mistaken. There is a check for connection first.

**Comment by EricBanker12** [comment]
will also require front end change to correct y axis. See https://github.com/tower-maze/frontend/commit/c10e193666ce5dc15b9b0b713b78dee21bd1c10f

**Comment by EricBanker12** [comment]
Will require changing room checks by id to by coordinates: see https://github.com/tower-maze/frontend/commit/f1bbd27540927025c7031a2c2e20b40b1bd20df8

**Review by wSedlacek — APPROVED** [review]
Looks good! Let's get this merged

**Pull request merged**
